//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNVEntities : DbContext
    {
        public QLNVEntities()
            : base("name=QLNVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Get_List_Staff_Info> Get_List_Staff_Info { get; set; }
    
        public virtual ObjectResult<string> Get_List_Place_Staff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_List_Place_Staff");
        }
    
        public virtual ObjectResult<string> Get_List_Place_By_Staff(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_List_Place_By_Staff", idParameter);
        }
    
        public virtual ObjectResult<Get_Table_By_Staff_Result> Get_Table_By_Staff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Table_By_Staff_Result>("Get_Table_By_Staff");
        }
    }
}
